services:
  whatsapp:
    image: quay.io/dioclecio/whatsapp-cron:latest
    volumes:
      - ./data:/app/data:rw
    environment:
      - "TZ=America/Sao_Paulo"
    security_opt:
      - "label=disable"
