networks:
  web:

services:
  whatsapp:
    image: whatsapp-cron:latest
    volumes:
      - .:/app:rw
      - ./data:/app/data:rw
    environment:
      - "TZ=America/Sao_Paulo"
      - PLAYWRIGHT_WS_ENDPOINT=ws://playwright:3000
    security_opt:
      - "label=disable"
    depends_on:
      - playwright
    networks:
      - web
    entrypoint: sleep infinity

  playwright:
    image: mcr.microsoft.com/playwright:v1.51.1
    # volumes:
    #   - ./data:/app/data:rw # Mount the data directory
    command: >
      /bin/sh -c "npx -y playwright@1.51.1 run-server --port 3000 --host 0.0.0.0"
    networks:
      - web
