networks:
    web:
services:
  browser:
    image: docker.io/selenium/standalone-chromium
    networks:
      - web
    ports:
      - "4444:4444"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - web
    environment:
      - SE_NODE_SESSION_TIMEOUT=999999999

  whatsapp:
    image: whatsapp-cron:latest
    volumes:
      - .:/app:rw
      - ./data:/app/data:rw
    networks:
      - web
    environment:
      - "SELENIUM_HUB=browser:4444"
      - "TZ=America/Sao_Paulo"
    security_opt:
      - "label=disable"
    entrypoint: sleep infinity

